baseURL = "https://www.openlifter.com/"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = "true"
title = "OpenLifter"
theme = "rusty"

[params]
  releaseVersion = "1.3"

[languages]
  [languages.de]
    languageName = "Deutsch"
    weight = 20
    [languages.de.params]
      placeholder = "Placeholder"

  [languages.en]
    languageName = "English"
    weight = 10
    [languages.en.params]
      placeholder = "Placeholder"

  [languages.eo]
    languageName = "Esperanto"
    weight = 20
    [languages.eo.params]
      placeholder = "Placeholder"

  [languages.es]
    languageName = "Español"
    weight = 20
    [languages.es.params]
      placeholder = "Placeholder"

  [languages.hr]
    languageName = "Hrvatski"
    weight = 20
    [languages.hr.params]
      placeholder = "Placeholder"

  [languages.nl]
    languageName = "Nederlands"
    weight = 20
    [languages.nl.params]
      placeholder = "Placeholder"

  [languages.pt]
    languageName = "Português"
    weight = 20
    [languages.pt.params]
      placeholder = "Placeholder"

  [languages.ru]
    languageName = "Русский"
    weight = 20
    [languages.ru.params]
      placeholder = "Placeholder"

  [languages.zh-Hans]
    languageName = "简体中文"
    weight = 20
    [languages.zh-Hans.params]
      placeholder = "Placeholder"
